#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		#bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'
		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' '' '9' '0'
		let name++
	done
}
workspaces

bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config focused_border_color "#4F4F4F" 
bspc config normal_border_color "#131a1c"
bspc config active_border_color "#131a1c"
bspc config presel_feedback_color "#131a1c"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle false
bspc config single_monocle false
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on bspc rule -a Screenkey manage=off


setxkbmap -layout us -variant dvp -option "caps:swapescape,grp:sclk_toggle"

$HOME/.local/scripts/start_picom
$HOME/.local/scripts/start_bar 
$HOME/.local/scripts/background

