#!/usr/bin/env zsh

alias vim="nvim"
alias vi="nvim"
alias ls="eza --icons"
alias bat="bat --color=auto"
alias cat="bat"
alias open="nautilus"
alias reader="zathura --fork"
alias lg="lazygit"
alias python="python3"
alias g="git"
alias k="kubectl"
alias rotate="xrandr --output HDMI-0 --mode 2560x1080 --rotate"
alias dotfiles="cd $HOME/.dotfiles/"
alias zkd="cd $ZK_NOTEBOOK_DIR"
alias taskd_init="TASKDDATA=\"/var/taskd\" \"/usr/local/bin/taskdctl\" start"
alias docker="podman"
alias lazydocker="DOCKER_HOST=unix:///run/user/1000/podman/podman.sock lazydocker"

v () {
  nvim $@
}

