#!/usr/bin/env zsh

export ZVM_VI_EDITOR="lvim"
export EDITOR="lvim"
export BROWSER="brave-browser"
export GOPATH=$HOME/dev/go/

export ANDROID_SDK_ROOT=$HOME/Android/Sdk/
export PATH=$PATH:$ANDROID_SDK_ROOT/emulator
export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
export REPOS=$HOME/dev/repos/MSBarbieri
export ZK_NOTEBOOK_DIR=$REPOS/zk_notes
export TASKDDATA=/var/taskd

# PATHS
addToPath $HOME/.local/bin
addToPath $HOME/.local/scripts
addToPath $HOME/dev/go/bin
addToPath /usr/local/go/bin
addToPath $HOME/.rd/bin
addToPath $HOME/.spicetify
addToPath $HOME/.emacs.d/bin

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# PYENV
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"


# GHCUP
[ -f "$HOME/.ghcup/env" ] && source "$HOME/.ghcup/env" # ghcup-env
