#!/bin/bash

echo "linking all dotfiles in your enviroment"

stow -vt ~ alacritty fonts git i3 "local" picom tmux \
  wallpapers zsh dunst scripts kitty taskwarrior nix

fc-cache
#sudo cp -f "$path/keyboard/default/keyboard" /etc/default/keyboard
#sudo cp -f "$path/keyboard/symbols/us" /usr/share/X11/xkb/symbols/us
