#!/bin/bash
stow -vt ~ alacritty fonts git i3 local lvim picom tmux \
    wallpapers zsh dunst scripts rust kitty taskwarrior

path=$(pwd)
sudo cp -f "$path/keyboard/default/keyboard" /etc/default/keyboard
sudo cp -f "$path/keyboard/symbols/us" /usr/share/X11/xkb/symbols/us

